# Generated by Django 6.1 on 2026-09-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsharetoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
